title = "Consumer Model"

[household]
# Number of persons in household - approx percentage for 1,2...7 people in USA - from Statista
household_sizes = [1,2,3,4,5,6,7]
household_size_distribution = [0.28,0.36,0.15,0.12,0.06,0.02,0.01]

# Consumption rate: number of steps per person neded to consume 1 product
# E.g. a consumption rate of 3 means that a product is consumed by one person in 3 steps
# Concretely, that could mean a tube of toothpaste takes 3 weeks to use per person
# Consumption rates are defined statistically via absolute value of a normal distribution
base_consumption_rate = 3

# Pantry minimum percent (percent of household size)
pantry_min_percent = 0.1 # when pantry drops below 20% of household size, consumer must buy to replenish

[brands]
# Base product price - the sticker price of a product
# Promo depths - the percentage of the base price that a promo reduces the price by
# Promo frequencies - the percentage of the time that a promo is offered
# Current market share - the percentage of the market that a brand currently has
# Advertising budget - the amount of money spent on advertising
# Advertising channels - the channels that a brand advertises on
# Advertising priority - the percentage of the budget that is spent on each channel
# Advertising campaigns - the campaigns that a brand runs, specifically the week numbers it is active
# Advertising spend structure - how budget is allocated over the course of a campaign

[brands.A]
name = "Brand A"
current_market_share = 0.6
base_product_price = 5.0
[brands.A.promotions]
promo_depths=[1.0, 0.75, 0.5]
promo_frequencies=[0.5, 0.25, 0.25]
promo_calendar = ["first_three_weeks_per_quarter", "holiday_season"]
[brands.A.advertising]
budget = 52000.0
channels = ["TV", "Web"]
priority = {TV = 40, Web = 60}
ad_campaigns = {TV = "first_three_weeks_per_quarter", Web = "holiday_season"}



[brands.B]
name = "Brand B"
current_market_share = 0.4
base_product_price = 5.0
[brands.B.promotions]
promo_depths=[1.0, 0.75, 0.5]
promo_frequencies=[0.5, 0.25, 0.25]
promo_calendar = ["first_three_weeks_per_quarter", "holiday_season"]
[brands.B.advertising]
budget = 48000.0
channels = ["TV", "Web"]
priority = {TV = 30, Web = 70}
ad_campaigns = {TV = "first_three_weeks_per_quarter", Web = "holiday_season"}

# You can add additional brands here

[ad_campaigns]
first_three_weeks_per_quarter = [1, 2, 3, 14, 15, 16, 27, 28, 29, 40, 41, 42]
holiday_season = [48, 49, 50, 51, 52]
back_to_school = [33, 34, 35]
summer_sale = [26, 27, 28, 29, 30]
black_friday = [47]
spring_sale = [14, 15, 16, 17, 18]  
valentines_day = [6, 7]  
easter_holiday = [13, 14]  
halloween = [44]  
cyber_monday = [48] 
# You can add custom campaigns here
