title = "Consumer Model"

[household]
# Household demographics (unchanged as these are based on real statistics)
household_sizes = [1,2,3,4,5,6,7]
household_size_distribution = [0.28,0.36,0.15,0.12,0.06,0.02,0.01]

# Consumption parameters
base_consumption_rate = 3
consumption_rate_override = 0

# Pantry management (unchanged)
pantry_min_percent = 0.1

# Channel preferences - adjusted for stronger digital presence
base_channel_preferences = {TV = 0.35, Web = 0.65}

# Advertising response parameters - adjusted for stronger effect
ad_decay_factor = 1.2
ad_decay_override = 0
adstock_incremental_sensitivty = 3.0
adstock_incremental_midpoint = 500.0

# Loyalty parameters - adjusted for more switching
loyalty_alpha = 10
loyalty_beta = 4
loyalty_rate_override = 0.6

# Purchase history window (unchanged)
purchase_history_range_lower = 3
purchase_history_range_upper = 6

# Price sensitivity parameters (unchanged)
price_increase_sensitivity = 5
price_decrease_sensitivity = 10
price_threshold = 0.01

[brands]
# Brand configurations

[brands.A]
name = "Brand A"
current_market_share = 0.50  # Adjusted to sum to 1.0 with Brand B
base_product_price = 5.0
[brands.A.promotions]
promo_calendar = {spring_sale = 0.90, back_to_school = 0.90}  # Added actual discounts
[brands.A.advertising]
budget = 2000000.0  # Increased budget
channels = ["TV", "Web"]
priority = {TV = 35, Web = 65}  # Aligned with channel preferences
ad_campaigns = {TV = "quick_lag_2", Web = "back_to_school"}

[brands.B]
name = "Brand B"
current_market_share = 0.50  # Adjusted to sum to 1.0 with Brand A
base_product_price = 5.0
[brands.B.promotions]
promo_calendar = {holiday_season = 0.90, summer_sale = 0.90}  # Added actual discounts
[brands.B.advertising]
budget = 1500000.0  # Added competitive budget
channels = ["TV", "Web"]
priority = {TV = 35, Web = 65}  # Aligned with channel preferences
ad_campaigns = {TV = "spring_sale", Web = "holiday_season"}

[campaign_library]
first_three_weeks_per_quarter = [1, 2, 3, 14, 15, 16, 27, 28, 29, 40, 41, 42]
holiday_season = [47, 48, 49, 50]
back_to_school = [32, 33, 34, 35]
summer_sale = [27, 28, 29, 30]
black_friday = [47]
spring_sale = [15, 16, 17, 18]  
valentines_day = [6, 7]  
easter_holiday = [13, 14]  
halloween = [44]  
cyber_monday = [48] 
quick_lag = [3,4,5]
quick_lag_2 = [5,6,7,8]